kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.19
    commands:
      - go build

  - name: test with success
    image: golang:1.19
    commands:
      - go test -v ./...

  - name: test with failure
    image: golang:1.19
    commands:
      - go test -v ./... --fail=$FAIL
    environment:
      FAIL: true

trigger:
  ref:
    - refs/heads/feature-*
    - refs/tags/*
